# Symptom encoding dictionaries for each column (example structure)

symptom_to_encoded = {
    's1':{ 
    'back_pain': 1,
    'acidity':0,
    'bladder_discomfort': 2,
    'breathlessness': 3,
    'burning_micturition':4,
    'chest_pain': 5,
    'chills': 6,
    'constipation': 7,
    'continuous_sneezing': 8,
    'cough': 9,
    'cramps': 10,
    'fatigue':11,
    'heacache':12,
    'high_fever': 13,
    'indigestion': 14,
    'joint_pain': 15,
    'mood_swings': 16,
    'muscle_wasting': 17,
    'muscle_weakness': 18,
    'neck_pain': 19,
    'pain_during_bowel_movements': 20,
    'patches_in_throat': 21,
    'pus_filled_pimples': 22,
    'shivering': 23,
    'skin_rash': 24,
    'stiff_neck': 25,
    'stomach_pain': 26,
    'sunken_eyes': 27,
    'vomiting':28,
    'weakness_in_limbs': 29,
    'weight_gain':30,
    'weight_loss':31,
    'yellowish_skin': 32,
    'itching': 33 
},
    
    's2': { 
        
    'abdominal_pain':0,
    'acidity':1,
    'anxiety': 2,
    'blackheads': 3,
    'bladder_discomfort':4,
    'blister':5,
    'breathlessness':6,
    'bruising':7,
    'chest_pain':8,
    'chills':9,
    'cold_hands_and_feets':10,
    'cough':11,
    'cramps':12,
    'dehydration': 13,
    'dizziness': 14,
    'fatigue':15,
    'foul_smell_of urine':16,
    'headache':17,
    'high_fever':18,
    'indigestion':19,
    'joint_pain':20,
    'knee_pain':21,
    'lethargy':22,
    'loss_of_appetite':23,
    'mood_swings':24,
    'nausea':25,
    'neck_pain': 26,
    'nodal_skin_eruptions':27,
    'pain_during_bowel_movements':28,
    'pain_in_anal_region':29,
    'patches_in_throat':30,
    'pus_filled_pimples':31,
    'restlessness':32,
    'shivering':33,
    'skin_peeling':34,
    'skin_rash':35,
    'stiff_neck':36,
    'stomach_pain':37,
    'sunken_eyes':38,
    'sweating':39,
    'swelling_joints':40,
    'ulcers_on_tongue':41,
    'vomiting':42,
    'weakness_in_limbs':43,
    'weakness_of_one_body_side':44,
    'weight_gain':45,
    'weight_loss':46,
    'yellowish_skin':47
    },
    
    
    's3': {
        
    'abdominal_pain': 0,  
    'altered_sensorium': 1,  
    'anxiety': 2,  
    'blackheads': 3,  
    'blister': 4,  
    'bloody_stool': 5,  
    'blurred_and_distorted_vision': 6,  
    'breathlessness': 7,  
    'bruising': 8,  
    'burning_micturition': 9,  
    'chest_pain': 10,  
    'chills': 11,  
    'cold_hands_and_feets': 12,  
    'continuous_feel_of_urine': 13,  
    'cough': 14,  
    'dark_urine': 15,  
    'dehydration': 16,  
    'diarrhoea': 17,  
    'dischromic_patches': 18,  
    'dizziness': 19,  
    'extra_marital_contacts': 20,  
    'fatigue': 21,  
    'foul_smell_of_urine': 22,  
    'headache': 23,  
    'high_fever': 24,  
    'hip_joint_pain': 25,  
    'joint_pain': 26,  
    'knee_pain': 27,  
    'lethargy': 28,  
    'loss_of_appetite': 29,  
    'loss_of_balance': 30,  
    'mood_swings': 31,  
    'movement_stiffness': 32,  
    'nausea': 33,  
    'neck_pain': 34,  
    'nodal_skin_eruptions': 35,  
    'obesity': 36,  
    'pain_in_anal_region': 37,  
    'red_sore_around_nose': 38,  
    'restlessness': 39,  
    'scurring': 40,  
    'silver_like_dusting': 41,  
    'skin_peeling': 42,  
    'spinning_movements': 43,  
    'stomach_pain': 44,  
    'sweating': 45,  
    'swelling_joints': 46,  
    'swelling_of_stomach': 47,  
    'ulcers_on_tongue': 48,  
    'vomiting': 49,  
    'watering_from_eyes': 50,  
    'weakness_of_one_body_side': 51,  
    'weight_loss': 52,  
    'yellowish_skin': 53
},
    
    's4': { 
        
    'abdominal_pain': 0,  
    'altered_sensorium': 1,  
    'bloody_stool': 2,  
    'blurred_and_distorted_vision': 3,  
    'breathlessness': 4,  
    'burning_micturition': 5,  
    'chest_pain': 6,  
    'continuous_feel_of_urine': 7,  
    'cough': 8,  
    'dark_urine': 9,  
    'diarrhoea': 10,  
    'dischromic_patches': 11,  
    'distention_of_abdomen': 12,  
    'dizziness': 13,  
    'excessive_hunger': 14,  
    'extra_marital_contacts': 15,  
    'family_history': 16,  
    'fatigue': 17,  
    'headache': 18,  
    'high_fever': 19,  
    'hip_joint_pain': 20,  
    'irregular_sugar_level': 21,  
    'irritation_in_anus': 22,  
    'lack_of_concentration': 23,  
    'lethargy': 24,  
    'loss_of_appetite': 25,  
    'loss_of_balance': 26,  
    'mood_swings': 27,  
    'movement_stiffness': 28,  
    'nausea': 29,  
    'obesity': 30,  
    'painful_walking': 31,  
    'passage_of_gases': 32,  
    'red_sore_around_nose': 33,  
    'restlessness': 34,  
    'scurring': 35,  
    'silver_like_dusting': 36,  
    'small_dents_in_nails': 37,  
    'spinning_movements': 38,  
    'spotting_ urination': 39,  
    'sweating': 40,  
    'swelling_joints': 41,  
    'swelling_of_stomach': 42,  
    'swollen_legs': 43,  
    'vomiting': 44,  
    'watering_from_eyes': 45,  
    'weight_loss': 46,  
    'yellow_crust_ooze': 47,  
    'yellowing_of_eyes': 48,  
    'yellowish_skin': 49,  
    'No Symptoms': 50
},
    
    's5': {
        
'abdominal_pain':0,
'blurred_and_distorted_vision': 1,
'breathlessness': 2,
'chest_pain': 3,
'cough': 4,
'dark_urine': 5,
'diarrhoea': 6,
'distention_of_abdomen': 7,
'dizziness': 8,
'excessive_hunger': 9,
'family_history': 10,
'fatigue': 11,
'headache': 12,
'high_fever': 13,
'history_of_alcohol_consumption': 14,
'inflammatory_nails': 15,
'internal_itching': 16,
'irregular_sugar_level': 17,
'irritation_in_anus': 18,
'lack_of_concentration': 19,
'lethargy': 20,
'loss_of_appetite': 21,
'loss_of_balance': 22,
'mucoid_sputum': 23,
'nausea': 24,
'painful_walking': 25,
'passage_of_gases': 26,
'small_dents_in_nails': 27,
'spotting_ urination': 28,
'stiff_neck': 29,
'sweating': 30,
'swelling_joints': 31,
'swollen_blood_vessels': 32,
'swollen_legs': 33,
'unsteadiness': 34,
'yellow_crust_ooze': 35,
'yellowing_of_eyes': 36,
'yellowish_skin': 37,
'No Symptoms': 38
},
    
    
    's6': {
        
'abdominal_pain': 0,
'blurred_and_distorted_vision': 1,
'breathlessness': 2,
'chest_pain': 3,
'constipation': 4,
'dark_urine': 5,
'depression': 6,
'diarrhoea': 7,
'dizziness': 8,
'family_history': 9,
'fast_heart_rate': 10,
'fluid_overload': 11,
'headache': 12,
'high_fever': 13,
'history_of_alcohol_consumption': 14,
'inflammatory_nails': 15,
'internal_itching': 16,
'loss_of_appetite': 17,
'malaise': 18,
'mucoid_sputum': 19,
'nausea': 20,
'obesity': 21,
'painful_walking': 22,
'prominent_veins_on_calf': 23,
'puffy_face_and_eyes': 24,
'stiff_neck': 25,
'sweating': 26,
'swelled_lymph_nodes': 27,
'swollen_blood_vessels': 28,
'unsteadiness': 29,
'yellowing_of_eyes': 30,
'yellowish_skin': 31,
'No Symptoms': 32
},
}

# Disease decoding dictionary with keys and values swapped
encoded_to_disease = {
    15: 'Fungal infection',
    4: 'Allergy',
    20: 'Hepatitis C',
    21: 'Hepatitis D',
    22: 'Hepatitis E',
    3: 'Alcoholic hepatitis',
    36: 'Tuberculosis',
    10: 'Common Cold',
    34: 'Pneumonia',
    13: 'Dimorphic hemorrhoids (piles)',
    39: 'Varicose veins',
    26: 'Hypothyroidism',
    25: 'Hypoglycemia',
    31: 'Osteoarthritis',
    5: 'Arthritis',
    0: '(vertigo) Paroxysmal Positional Vertigo',
    2: 'Acne',
    38: 'Urinary tract infection',
    35: 'Psoriasis',
    27: 'Impetigo',
    16: 'GERD',
    9: 'Chronic cholestasis',
    14: 'Drug Reaction',
    33: 'Peptic ulcer disease',
    1: 'AIDS',
    12: 'Diabetes',
    17: 'Gastroenteritis',
    6: 'Bronchial Asthma',
    23: 'Hypertension',
    30: 'Migraine',
    7: 'Cervical spondylosis',
    32: 'Paralysis (brain hemorrhage)',
    28: 'Jaundice',
    29: 'Malaria',
    8: 'Chicken pox',  
    11: 'Dengue',
    37: 'Typhoid',
    40: 'Hepatitis A',
    19: 'Hepatitis B',
    18: 'Heart attack',
    24: 'Hyperthyroidism'
}
